### ISSUE TITLE
Ubuntu 19.10 not working

### ISSUE THREAD

**Issue by marcolaux** [maze-n/gnome-shell-extension-daynight#2]
Hello and good day,

I got this error:

```
JS ERROR: Extension daynight@maze-n.github.com: Error: GSettings schema org.gnome.shell.extensions.user-theme not found
                                               _init@resource:///org/gnome/gjs/modules/overrides/Gio.js:550:27
                                               @/home/USER/.local/share/gnome-shell/extensions/daynight@maze-n.github.com/extension.js:40:22
                                               _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:331:13
                                               loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:261:22
                                               callback@resource:///org/gnome/shell/ui/extensionDownloader.js:244:17
                                               gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:108:13
gnome-software[6149]: State change on user/*/*/shell-extension/daynight_maze-n.github.com/* from available to installed is not OK
gnome-software[6149]: daynight_maze-n.github.com has error: Error: GSettings schema org.gnome.shell.extensions.user-theme not found

```

I have "user-themes" installed but it seems there is no gsettings scheme. My dconf-editor looks like this:

![Bildschirmfoto von 2019-11-27 12-29-22](https://user-images.githubusercontent.com/6410852/69719812-94fdd200-1111-11ea-8769-bf026a666c44.png)

The key is there but it says "no scheme found"

The extension user-themes works - I tried a custom shell theme and it applies.

Thanks in advance and all the best.

**Comment by maze-n** [comment]
Thanks for opening the issue!!
I was able to recreate this problem and I think running these commands will fix it

`sudo  cp ~/.local/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com/org.gnome.shell.extensions.user-theme.gschema.xml /usr/share/glib-2.0/schemas`

`sudo glib-compile-schemas /usr/share/glib-2.0/schemas`

I don't know why the gsettings schema was not automatically added like most of the time.

**Comment by marcolaux** [comment]
Thank you for the reply.

I think this is should not be the right way to solve the problem (especially for unexperienced users).

You could propapbly look at the "impatience" extension. There is an alternative route for getting some settings even if the schema is not available system wide.

**Comment by maze-n** [comment]
Yeah you're right. I'm an amateur in gnome extension developing and this is my first extension :grin: . 

Eventhough my methods are kinda wrong(as a beginner im not that familiar with all the functions in gnome), that schema is supposed to be available after installing 'user-theme' extension.
